'use client'

/**
 * The full-width editorial product sections — the large blocks with the photo, the copy,
 * the "Passer for" tags, the quantity price table, the documents and the "Meld interesse"
 * button.
 *
 * Extracted from `BedrifterClient` so /bedrifter and the package pages under
 * /bedrifter/<slug> render the very same blocks from the very same data: a price, a
 * document or a line of copy changes in one place and both routes follow. The pages differ
 * only in which products they pass in and in what their buttons do with the click — those
 * arrive as props, so nothing here knows which route it is on.
 */

import Image from 'next/image'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { formatPrice } from '@/lib/format'
import { buildPriceTableRows, quoteThresholdFor, type PriceTableRow } from '@/lib/quantityPricing'
import { QUOTE_TEXT } from '@/lib/quoteRequest'
import {
  bedrifterDocuments,
  bedrifterProductKey,
  type DocumentAnchor,
  type DocumentFile,
  type ProductDocument,
} from '@/lib/bedrifterDocuments'
import type { BedrifterProduct } from '@/lib/bedrifterProducts'
import { productSectionAnchorId } from '@/lib/productAnchor'
import {
  ANCHOR_OFFSET,
  BORDER_WARM,
  INK,
  MUTED,
  OLIVE,
  SAGE,
  SANS,
  SERIF,
  SOFT,
  cardLabelStyle,
} from './theme'
import type { RevealProps } from './useReveal'

/** One editorial product section. Every product on the page uses this shape. */
export interface ProductSection {
  name: string
  subtitle: string
  description: string
  suitableFor: string[]
  image: string
  imageAlt: string
  /** The catalogue photography is square. */
  imageAspect: string
  /** Product page the image links to. */
  href?: string
  /** Value the "Meld interesse" button presets in the form's dropdown. */
  interestOption: string
  /** Produktark, Prisliste and Tilbudsmal, resolved to the product's files in Blob. */
  documents: ProductDocument[]
  /**
   * The product's quantity price bands, generated by the shared pricing engine from its live
   * CMS price. There is deliberately no B2B price table written into this page — every figure
   * below comes from the same table the cart and the checkout charge from, so a price can
   * never be advertised here that the shop does not actually apply.
   *
   * A product with no configured bands gets a single open-ended row, which is the truth for
   * it, and no quote row.
   */
  priceTable: PriceTableRow[]
  /** The quantity the quote row's CTA asks about — the threshold itself. */
  quoteQuantity: number | null
}

/**
 * Page-specific copy for the catalogue models, keyed by slug. Everything else — title,
 * description, photo and URL — is read from Payload, so the product data lives in one place.
 * A product without an entry here still renders, using its CMS tagline as the subtitle.
 */
const CATALOGUE_COPY: Record<
  string,
  {
    subtitle: string
    suitableFor: string[]
    /** Replaces the CMS description where this page needs shorter, workplace-facing copy. */
    description?: string
    /** Model-specific value for the form's dropdown; the rest share the generic option. */
    interestOption?: string
  }
> = {
  aboks: {
    subtitle: 'For komplett oppbevaring av AA- og AAA-batterier',
    suitableFor: ['Kontor', 'Arbeidsplass', 'Fellesområder', 'Lager'],
  },
  'aboks-mini': {
    subtitle: 'Kompakt oppbevaring for AA-batterier',
    suitableFor: ['Kontor', 'Verksted', 'Resepsjon', 'Små arbeidsplasser'],
  },
  'aboks-nano': {
    subtitle: 'Kompakt oppbevaring for AAA-batterier',
    suitableFor: ['Kontor', 'Skoler og institusjoner', 'Små arbeidsplasser'],
  },
  'aboks-vegg': {
    subtitle: 'For plassbesparende oppbevaring på veggen',
    suitableFor: ['Verksted', 'Lager', 'Produksjon', 'Fellesområder'],
  },
  // The CMS description is written for private customers; the workplace copy this page
  // used while the model was still upcoming is kept here instead.
  'aboks-spesial': {
    subtitle: 'For trygg innsamling av brukte batterier',
    description:
      'En veggmontert beholder med ekstra kapasitet for brukte batterier. Utviklet for bedrifter og arbeidsplasser der batterier skiftes ofte og det er behov for flere lett tilgjengelige innsamlingspunkter.',
    suitableFor: ['Produksjon', 'Verksted', 'Lager', 'Kontor', 'Skoler og institusjoner'],
    interestOption: 'aBoks Spesial',
  },
  // Both models are in the CMS with copy written for the product page; the workplace-facing
  // subtitle, the "Passer for" list and the dropdown option are page-specific, so they live
  // here — exactly as they do for aBoks Spesial above.
  'aboks-xl': {
    subtitle: 'For sentral innsamling av brukte batterier i større virksomheter.',
    suitableFor: [
      'Kommuner',
      'Skoler',
      'Sykehjem',
      'Kontorbygg',
      'Fabrikker',
      'Institusjoner',
      'Fellesområder',
    ],
    interestOption: 'aBoks XL',
  },
  'aboks-office': {
    subtitle: 'Orden på skrivebordet – med plass til batterier, mobil og kontorutstyr.',
    suitableFor: ['Kontorer', 'Hjemmekontor', 'Møterom', 'Resepsjon', 'Arbeidsplasser'],
    interestOption: 'aBoks Office',
  },
}

function Tag({ children }: { children: React.ReactNode }) {
  return (
    <li
      style={{
        fontFamily: SANS,
        fontSize: '13px',
        fontWeight: 600,
        color: '#4a4e41',
        border: `1px solid ${BORDER_WARM}`,
        borderRadius: '999px',
        padding: '7px 15px',
        background: 'rgba(255,255,255,.5)',
      }}
    >
      {children}
    </li>
  )
}

function FileIcon() {
  return (
    <svg
      aria-hidden="true"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.6"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{ flexShrink: 0 }}
    >
      <path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z" />
      <path d="M14 3v5h5" />
    </svg>
  )
}

function DownloadIcon() {
  return (
    <svg
      aria-hidden="true"
      width="15"
      height="15"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{ flexShrink: 0 }}
    >
      <path d="M12 4v11" />
      <path d="m7.5 10.5 4.5 4.5 4.5-4.5" />
      <path d="M5 19h14" />
    </svg>
  )
}

function ExternalLinkIcon() {
  return (
    <svg
      aria-hidden="true"
      width="15"
      height="15"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{ flexShrink: 0 }}
    >
      <path d="M14 5h5v5" />
      <path d="m19 5-8 8" />
      <path d="M18 14v4a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4" />
    </svg>
  )
}

/** Marks a document row that leads somewhere on the page instead of to a file. */
function ArrowRightIcon() {
  return (
    <svg
      aria-hidden="true"
      width="15"
      height="15"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.7"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{ flexShrink: 0 }}
    >
      <path d="M5 12h13" />
      <path d="m12.5 6 6 6-6 6" />
    </svg>
  )
}

/** The small uppercase format label on the right of a document row ("PDF", "HTML"). */
const fileTypeStyle: React.CSSProperties = {
  flexShrink: 0,
  fontFamily: SANS,
  fontWeight: 700,
  fontSize: '11px',
  letterSpacing: '0.12em',
  color: MUTED,
}

/** The document's name, filling the row so the format label is pushed to the far right. */
const documentNameStyle: React.CSSProperties = {
  flex: 1,
  minWidth: 0,
  fontFamily: SANS,
  fontWeight: 600,
  fontSize: '14.5px',
  lineHeight: 1.3,
  color: 'inherit',
}

/** Shared by both kinds of full-width row, so a file row and an anchor row sit alike. */
const documentRowStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '11px',
  flex: 1,
  minWidth: 0,
  padding: '12px 10px',
  textDecoration: 'none',
  transition: 'background .18s ease, color .18s ease',
}

/**
 * Document rows inside a solution card, one row per document. A row's first format claims
 * the whole row — icon, label and all — so clicking anywhere on it downloads the PDF. Any
 * further format (today only the Tilbudsmal's browser version) sits to its right as a
 * separate link, giving the `PDF ↓  HTML ↗` pairing.
 *
 * A row carrying an `anchor` instead of files (the Prisliste) keeps the same shape but
 * leads to the inquiry form, ending in `Be om tilbud →` where the others end in `PDF ↓`.
 */
function DocumentList({
  documents,
  productName,
  onAnchorClick,
}: {
  documents: ProductDocument[]
  productName: string
  /** Handles a click on an anchor row: presets the form and runs the scroll. */
  onAnchorClick: React.MouseEventHandler<HTMLAnchorElement>
}) {
  return (
    <div style={{ width: '100%', margin: '0 0 30px' }}>
      <p style={cardLabelStyle}>Dokumenter</p>
      <ul
        style={{
          listStyle: 'none',
          margin: 0,
          padding: 0,
          width: '100%',
          borderTop: `1px solid ${BORDER_WARM}`,
        }}
      >
        {documents.map((doc) => {
          const [primary, ...secondary] = doc.files
          return (
            <li
              key={doc.label}
              style={{ borderBottom: `1px solid ${BORDER_WARM}`, display: 'flex', alignItems: 'stretch' }}
            >
              {doc.anchor ? (
                <DocumentAnchorLink
                  anchor={doc.anchor}
                  documentLabel={doc.label}
                  productName={productName}
                  onClick={onAnchorClick}
                />
              ) : (
                <DocumentLink file={primary} documentLabel={doc.label} productName={productName} primary>
                  <FileIcon />
                  <span style={documentNameStyle}>{doc.label}</span>
                </DocumentLink>
              )}

              {secondary.map((file) => (
                <span key={file.type} style={{ display: 'flex', alignItems: 'stretch' }}>
                  <span
                    aria-hidden="true"
                    style={{ width: '1px', background: BORDER_WARM, margin: '9px 0', flexShrink: 0 }}
                  />
                  <DocumentLink file={file} documentLabel={doc.label} productName={productName} />
                </span>
              ))}
            </li>
          )
        })}
      </ul>
    </div>
  )
}

/**
 * One format of one document. `primary` makes it fill the remaining row width so the row
 * itself is the click target; otherwise it is a compact `HTML ↗` link at the end.
 *
 * PDFs download (the URL carries Blob's own `?download=1`), HTML opens in a new tab so the
 * customer can fill the template in and use its print button.
 */
function DocumentLink({
  file,
  documentLabel,
  productName,
  primary = false,
  children,
}: {
  file: DocumentFile
  documentLabel: string
  productName: string
  primary?: boolean
  children?: React.ReactNode
}) {
  const opens = file.action === 'open'
  return (
    <a
      href={file.url}
      data-btn
      className="abx-doc-row"
      {...(opens
        ? { target: '_blank', rel: 'noopener noreferrer' }
        : { download: true })}
      aria-label={
        opens
          ? `Åpne ${productName} ${documentLabel.toLowerCase()} i nettleseren`
          : `Last ned ${productName} ${documentLabel.toLowerCase()} som ${file.type}`
      }
      style={
        primary
          ? documentRowStyle
          : { ...documentRowStyle, gap: '7px', flex: '0 0 auto', padding: '12px 10px 12px 12px' }
      }
    >
      {children}
      <span className="abx-doc-type" style={fileTypeStyle}>
        {file.type}
      </span>
      {opens ? <ExternalLinkIcon /> : <DownloadIcon />}
    </a>
  )
}

/**
 * The Prisliste row. There is no public price sheet to download — the price depends on the
 * order — so the row keeps a file row's shape and sends the visitor to the inquiry form,
 * preselecting this product on the way.
 *
 * The `href` is a real in-page anchor, so a middle click, `/bedrifter#tilbud` typed by hand
 * and the no-JS case all still land on the form; `onClick` only takes over a plain left
 * click to run the site's own smooth scroll.
 */
function DocumentAnchorLink({
  anchor,
  documentLabel,
  productName,
  onClick,
}: {
  anchor: DocumentAnchor
  documentLabel: string
  productName: string
  onClick: React.MouseEventHandler<HTMLAnchorElement>
}) {
  return (
    <a
      href={`#${anchor.id}`}
      data-btn
      className="abx-doc-row"
      onClick={onClick}
      aria-label={`${documentLabel} for ${productName} — ${anchor.label.toLowerCase()} i skjemaet nedenfor`}
      style={documentRowStyle}
    >
      <FileIcon />
      <span style={documentNameStyle}>{documentLabel}</span>
      <span className="abx-doc-type" style={{ ...fileTypeStyle, whiteSpace: 'nowrap' }}>
        {anchor.label}
      </span>
      <ArrowRightIcon />
    </a>
  )
}

/**
 * One product's quantity prices.
 *
 * Every row is generated — see `BedrifterProduct.priceTable`. The last row is the quote row:
 * it carries the same unit price as the row above it, because reaching the quote threshold is
 * not a further reduction, and offers the enquiry instead of repeating the amount.
 */
function PriceTable({
  rows,
  productName,
  quoteHref,
  onQuoteRequest,
}: {
  rows: PriceTableRow[]
  productName: string
  /** Where the quote row points. A real anchor, so a middle click still lands somewhere. */
  quoteHref: string
  /** Presets the form with this product and the quote quantity, then scrolls to it. */
  onQuoteRequest: React.MouseEventHandler<HTMLAnchorElement>
}) {
  // A single open-ended row is a product with no quantity pricing — there is no table to show.
  if (rows.length < 2) return null
  // A product whose price could not be read would print a table of «kr 0». Better nothing.
  if (rows.some((row) => !(row.unitPrice > 0))) return null

  return (
    <div style={{ width: '100%', margin: '0 0 30px' }}>
      <p style={cardLabelStyle}>Pris per stk.</p>
      <table
        style={{
          width: '100%',
          borderCollapse: 'collapse',
          fontFamily: SANS,
          fontSize: '14.5px',
        }}
      >
        <caption className="sr-only">Mengdepriser for {productName}, eks. frakt</caption>
        <thead>
          <tr>
            <th
              scope="col"
              style={{
                textAlign: 'left',
                padding: '0 0 8px',
                fontWeight: 600,
                fontSize: '12.5px',
                letterSpacing: '0.04em',
                textTransform: 'uppercase',
                color: MUTED,
              }}
            >
              Antall
            </th>
            <th
              scope="col"
              style={{
                textAlign: 'right',
                padding: '0 0 8px',
                fontWeight: 600,
                fontSize: '12.5px',
                letterSpacing: '0.04em',
                textTransform: 'uppercase',
                color: MUTED,
              }}
            >
              Pris per stk.
            </th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.range} style={{ borderTop: `1px solid ${BORDER_WARM}99` }}>
              <th
                scope="row"
                style={{ textAlign: 'left', padding: '11px 0', fontWeight: 600, color: INK }}
              >
                {row.range}
              </th>
              <td style={{ textAlign: 'right', padding: '11px 0', color: INK }}>
                {row.isQuoteRow ? (
                  // The published price still applies here — the link is an addition, not a
                  // replacement, and the amount is repeated so nothing looks withheld.
                  <span style={{ display: 'inline-flex', alignItems: 'baseline', gap: '10px', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                    <span style={{ color: MUTED }}>{formatPrice(row.unitPrice)}</span>
                    <a
                      href={quoteHref}
                      data-btn
                      onClick={onQuoteRequest}
                      style={{
                        fontWeight: 600,
                        color: OLIVE,
                        textDecoration: 'underline',
                        textUnderlineOffset: '3px',
                      }}
                    >
                      {QUOTE_TEXT.cta}
                    </a>
                  </span>
                ) : (
                  <span style={{ fontWeight: 600 }}>{formatPrice(row.unitPrice)}</span>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <p
        style={{
          fontFamily: SANS,
          fontSize: '12.5px',
          lineHeight: 1.6,
          color: MUTED,
          margin: '10px 0 0',
        }}
      >
        Prisene er inkl. mva. og gjelder per produkt — antall av ulike produkter legges ikke
        sammen. Prisen gjelder alle enhetene i bestillingen.
      </p>
    </div>
  )
}

/**
 * Rules the product sections need that inline styles cannot express — hover, focus and the
 * global press effect. Rendered once for the whole page rather than per section.
 */
const PRODUCT_SECTION_CSS = `
  /* Base colours live here, not inline, so the hover rule below can win. */
  html[data-site="frontend"] .abx-doc-row {
    background: transparent;
    color: ${SOFT};
  }
  /* The format label stays muted until its own link is hovered. */
  @media (hover: hover) {
    html[data-site="frontend"] .abx-doc-row:hover .abx-doc-type {
      color: inherit;
    }
  }
  html[data-site="frontend"] .abx-doc-row:active {
    transform: none !important;
    filter: none !important;
  }
  html[data-site="frontend"] .abx-doc-row:focus-visible,
  html[data-site="frontend"] .abx-product-image:focus-visible {
    outline: 2px solid ${SAGE};
    outline-offset: -2px;
    border-radius: 8px;
  }
  html[data-site="frontend"] .abx-product-image:focus-visible {
    border-radius: 26px;
  }
  @media (hover: hover) {
    html[data-site="frontend"] .abx-doc-row:hover {
      background: rgba(94,106,72,.055);
      color: ${OLIVE};
    }
  }
`

/**
 * One full-width editorial product section: image in one column, copy in the other,
 * sides alternating down the page. Every product on the page renders through this.
 *
 * Below `md` the text wrapper is `display: contents`, so the intro group, the image and the
 * body become siblings in the single-column grid and the intro can be ordered above the
 * image. From `md` it is a normal flex column and the two-column layout is untouched.
 */
function ProductSectionBlock({
  section,
  anchorId,
  imageFirst,
  reveal,
  quoteHref,
  onInterest,
  onDocumentRequest,
  onPriceTableQuote,
}: {
  section: ProductSection
  /**
   * The section's `id`, on a page that links to it from elsewhere. `scroll-margin-top`
   * comes with it, so the heading clears the fixed header. Undefined on a page that does
   * not link to its sections, which then renders exactly the markup it always has.
   */
  anchorId?: string
  imageFirst: boolean
  reveal: (delay?: number) => RevealProps
  /** Where the price table's quote row points on this page. */
  quoteHref: string
  /** Presets the form's dropdown and takes over the scroll to `#foresporsel`. */
  onInterest: React.MouseEventHandler<HTMLAnchorElement>
  /** The same, for the Prisliste row's `#tilbud` link straight to the form itself. */
  onDocumentRequest: React.MouseEventHandler<HTMLAnchorElement>
  /** The price table's quote row — presets the product and the quote quantity too. */
  onPriceTableQuote: React.MouseEventHandler<HTMLAnchorElement>
}) {
  const image = (
    <Image
      src={section.image}
      alt={section.imageAlt}
      fill
      sizes="(max-width: 768px) 100vw, 50vw"
      className="object-cover transition-transform duration-500 ease-out"
    />
  )

  return (
    <div
      id={anchorId}
      className="grid grid-cols-1 md:grid-cols-2"
      style={{
        columnGap: 'clamp(32px,4.5vw,72px)',
        rowGap: 'clamp(28px,4vw,40px)',
        alignItems: 'center',
        ...(anchorId ? { scrollMarginTop: ANCHOR_OFFSET } : null),
      }}
    >
      <motion.div
        {...reveal()}
        className={imageFirst ? 'md:order-1' : 'md:order-2'}
        style={{
          position: 'relative',
          aspectRatio: section.imageAspect,
          borderRadius: '26px',
          overflow: 'hidden',
          background: '#efe6d3',
          boxShadow: '0 24px 48px -22px rgba(42,36,24,.24)',
        }}
      >
        {section.href ? (
          // `data-btn` opts out of the global link-hover fade; the frame keeps its own
          // subtle zoom instead. The whole image is the target.
          <Link
            href={section.href}
            data-btn
            aria-label={`Se ${section.name}`}
            className="abx-product-image group absolute inset-0 block"
          >
            <span className="absolute inset-0 block transition-transform duration-500 ease-out group-hover:scale-[1.03]">
              {image}
            </span>
          </Link>
        ) : (
          image
        )}
      </motion.div>

      <div className={`contents md:flex md:flex-col ${imageFirst ? 'md:order-2' : 'md:order-1'}`}>
        {/* Title and subtitle stay together as one compact intro group.
            `order: -1` lifts it above the image on mobile and keeps it first in
            the desktop column, where it is the natural DOM order anyway. */}
        <motion.div
          {...reveal(0.1)}
          className="md:mb-6"
          style={{ order: -1, display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}
        >
          <h3
            style={{
              fontFamily: SERIF,
              fontWeight: 500,
              fontSize: 'clamp(30px,3.4vw,46px)',
              letterSpacing: '-0.02em',
              lineHeight: 1.05,
              color: INK,
              margin: '22px 0 12px',
            }}
          >
            {section.name}
          </h3>
          {/* The 24px that used to sit under the subtitle now lives on the intro
              group at `md` — on mobile the grid's row gap handles it instead. */}
          <p
            style={{
              fontFamily: SERIF,
              fontStyle: 'italic',
              fontWeight: 500,
              fontSize: 'clamp(20px,2vw,27px)',
              lineHeight: 1.28,
              letterSpacing: '-0.01em',
              color: OLIVE,
              margin: 0,
            }}
          >
            {section.subtitle}
          </p>
        </motion.div>

        {/* Body — divider, description, tags, documents and CTA. */}
        <motion.div
          {...reveal(0.1)}
          style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}
        >
          <div style={{ height: '1px', background: BORDER_WARM, width: '100%', margin: '0 0 24px' }} />
          <p
            style={{
              fontFamily: SANS,
              fontSize: 'clamp(15.5px,1.3vw,17px)',
              lineHeight: 1.7,
              color: SOFT,
              margin: '0 0 26px',
              maxWidth: '54ch',
            }}
          >
            {section.description}
          </p>

          {section.suitableFor.length > 0 && (
            <>
              <p style={cardLabelStyle}>Passer for</p>
              <ul
                style={{
                  listStyle: 'none',
                  display: 'flex',
                  flexWrap: 'wrap',
                  gap: '9px',
                  margin: '0 0 30px',
                  padding: 0,
                }}
              >
                {section.suitableFor.map((item) => (
                  <Tag key={item}>{item}</Tag>
                ))}
              </ul>
            </>
          )}

          <PriceTable
            rows={section.priceTable}
            productName={section.name}
            quoteHref={quoteHref}
            onQuoteRequest={onPriceTableQuote}
          />

          {section.documents.length > 0 && (
            <DocumentList
              documents={section.documents}
              productName={section.name}
              onAnchorClick={onDocumentRequest}
            />
          )}

          <a
            href="#foresporsel"
            data-btn
            onClick={onInterest}
            className="w-full justify-center sm:w-auto"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '15px 32px',
              borderRadius: '999px',
              border: `1.5px solid ${OLIVE}`,
              color: OLIVE,
              fontFamily: SANS,
              fontWeight: 600,
              fontSize: '15px',
              textDecoration: 'none',
              minHeight: '52px',
            }}
          >
            Meld interesse
          </a>
        </motion.div>
      </div>
    </div>
  )
}

/** A product section together with the catalogue entry it was built from. */
export type BedrifterProductSection = ProductSection & { product: BedrifterProduct }

/**
 * Every product handed in, as an editorial section, in the order they arrive. Each entry
 * carries its own product page, so its photo links there.
 *
 * The one place a `BedrifterProduct` becomes a section: /bedrifter builds the whole
 * catalogue this way and a package page builds its own products, so neither can drift.
 */
export function buildProductSections(products: BedrifterProduct[]): BedrifterProductSection[] {
  return products.map((product) => {
    const copy = CATALOGUE_COPY[product.slug]
    // A future CMS product with no files in the Blob folder simply renders without the
    // "Dokumenter" block rather than with links that 404.
    const documentKey = bedrifterProductKey(product.slug)
    return {
      product,
      // Generated from the shared engine, never restated here. The quote row's quantity is
      // the threshold itself, so the enquiry it opens asks about the quantity it names.
      priceTable: buildPriceTableRows(product),
      quoteQuantity: quoteThresholdFor(product),
      name: product.title,
      subtitle: copy?.subtitle ?? product.tagline,
      description: copy?.description ?? (product.description || product.tagline),
      suitableFor: copy?.suitableFor ?? [],
      image: product.image,
      imageAlt: product.imageAlt,
      // The catalogue photography is square — a 4:3 crop would cut into the products.
      imageAspect: '1 / 1',
      href: `/produkter/${product.slug}`,
      // The form's dropdown carries a per-model option only for some of the catalogue.
      interestOption: copy?.interestOption ?? 'Produkter til egen bedrift',
      documents: documentKey ? bedrifterDocuments(documentKey) : [],
    }
  })
}

/**
 * The sections one after another, sides alternating, with the rules they need rendered
 * once above them.
 *
 * Each handler is a factory taking the section, because every button acts on the product it
 * belongs to. The page decides what a click does — which form it fills and which anchor it
 * scrolls to — so /bedrifter keeps its own behaviour and a package page can send the same
 * buttons to its own inquiry form.
 */
export default function ProductSectionList({
  sections,
  reveal,
  quoteHref = '#tilbud',
  withAnchorIds = false,
  onInterest,
  onDocumentRequest,
  onPriceTableQuote,
}: {
  sections: BedrifterProductSection[]
  reveal: (delay?: number) => RevealProps
  /**
   * Where the price tables' quote rows point. The default is /bedrifter's own `#tilbud`
   * block; a page whose form sits behind a different anchor passes its own, so the link is
   * never a hash that page does not have.
   */
  quoteHref?: string
  /**
   * Gives every section the `id` `productSectionAnchorId` derives from its slug, so the
   * page can link down to it. A package page turns this on for its configurator's
   * "Se produktdetaljer" links; /bedrifter has nothing linking to its sections and leaves
   * them as they are.
   */
  withAnchorIds?: boolean
  /** "Meld interesse" — the form's dropdown, preset to this product. */
  onInterest: (section: BedrifterProductSection) => React.MouseEventHandler<HTMLAnchorElement>
  /** A document row that asks for something instead of handing over a file. */
  onDocumentRequest: (section: BedrifterProductSection) => React.MouseEventHandler<HTMLAnchorElement>
  /** The price table's quote row — the product and the quantity it names. */
  onPriceTableQuote: (section: BedrifterProductSection) => React.MouseEventHandler<HTMLAnchorElement>
}) {
  return (
    <>
      <style>{PRODUCT_SECTION_CSS}</style>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'clamp(64px,8vw,112px)' }}>
        {sections.map((section, index) => (
          <ProductSectionBlock
            key={section.name}
            section={section}
            anchorId={withAnchorIds ? productSectionAnchorId(section.product.slug) : undefined}
            imageFirst={index % 2 === 0}
            reveal={reveal}
            quoteHref={quoteHref}
            onInterest={onInterest(section)}
            onDocumentRequest={onDocumentRequest(section)}
            onPriceTableQuote={onPriceTableQuote(section)}
          />
        ))}
      </div>
    </>
  )
}
