/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    'product-variants': ProductVariant;
    media: Media;
    orders: Order;
    'promo-codes': PromoCode;
    'promo-code-usages': PromoCodeUsage;
    'partner-payouts': PartnerPayout;
    customers: Customer;
    'marketing-expenses': MarketingExpense;
    reviews: Review;
    'review-invitations': ReviewInvitation;
    'review-photos': ReviewPhoto;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    'promo-code-usages': PromoCodeUsagesSelect<false> | PromoCodeUsagesSelect<true>;
    'partner-payouts': PartnerPayoutsSelect<false> | PartnerPayoutsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'marketing-expenses': MarketingExpensesSelect<false> | MarketingExpensesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'review-invitations': ReviewInvitationsSelect<false> | ReviewInvitationsSelect<true>;
    'review-photos': ReviewPhotosSelect<false> | ReviewPhotosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'economy-settings': EconomySetting;
    'tiktok-connection': TiktokConnection;
    'pinterest-connection': PinterestConnection;
  };
  globalsSelect: {
    'economy-settings': EconomySettingsSelect<false> | EconomySettingsSelect<true>;
    'tiktok-connection': TiktokConnectionSelect<false> | TiktokConnectionSelect<true>;
    'pinterest-connection': PinterestConnectionSelect<false> | PinterestConnectionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Administrer produkter i butikken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Brukes i URL-en: /produkter/[slug]
   */
  slug: string;
  /**
   * Vises under produktnavnet på produktsiden.
   */
  tagline?: string | null;
  description: string;
  /**
   * Pris i norske kroner (eks. 499)
   */
  price: number;
  /**
   * Antall enheter på lager. Brukes kun for produkter uten fargevarianter — har produktet varianter, styres lageret på hver variant.
   */
  stock?: number | null;
  /**
   * Legg til kostnadsposter (uten MVA). Total kostpris regnes ut automatisk som summen.
   */
  costItems?:
    | {
        name: string;
        /**
         * Kostnad i NOK, uten MVA.
         */
        amount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Regnes automatisk ut som summen av alle kostnadsposter (kr, uten MVA).
   */
  costPrice?: number | null;
  /**
   * Første bilde brukes som hovedbilde.
   */
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  capacity?: {
    aa?: number | null;
    aaa?: number | null;
    usedCompartments?: number | null;
  };
  features?:
    | {
        number?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Seksjoner som vises i akkordeon under kjøpsknappen (f.eks. Beskrivelse, Spesifikasjoner, Frakt og retur). Du kan endre rekkefølge, legge til og slette seksjoner fritt.
   */
  details?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Velg produkter som skal vises som anbefalinger når dette produktet ligger i handlekurven.
   */
  cartRecommendations?: (number | Product)[] | null;
  /**
   * Tilbudspris i kr. Sett lavere enn ordinær pris for å aktivere rabatt. La stå tom for ingen rabatt.
   */
  salePrice?: number | null;
  /**
   * La stå tom for å starte umiddelbart.
   */
  saleStartDate?: string | null;
  /**
   * La stå tom for at tilbudet aldri utløper.
   */
  saleEndDate?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Styrer hvor produktet vises: /produkter eller /tilbehor.
   */
  section: 'products' | 'accessories';
  /**
   * Kryss av for å vise produktet i butikken.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Fargevarianter for produkter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  /**
   * Genereres automatisk: «Produktnavn – Fargenavn». Kan ikke redigeres manuelt.
   */
  displayName?: string | null;
  product: number | Product;
  /**
   * F.eks. Olivengrønn, Mørk blå, Sort
   */
  name: string;
  /**
   * F.eks. #5b6347
   */
  colorHex: string;
  image?: (number | null) | Media;
  sku: string;
  /**
   * Antall enheter på lager.
   */
  inventory: number;
  /**
   * Lavere tall vises først.
   */
  sortOrder?: number | null;
  /**
   * Full URL til .mp4-produktvideo for denne fargen. La stå tom hvis ingen video. Videoen lastes først når kunden trykker play – last derfor opp et stillbilde ved siden av filen med samme navn og endelsen -poster.webp (f.eks. aBoks-sort-video.mp4 → aBoks-sort-video-poster.webp).
   */
  videoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Alle bestillinger fra nettbutikken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Genereres automatisk når ordren lagres.
   */
  orderNumber: string;
  kustomOrderId?: string | null;
  customer?: (number | null) | Customer;
  customerInfo?: {
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    address?: string | null;
    postalCode?: string | null;
    city?: string | null;
    phone?: string | null;
  };
  items: {
    product?: (number | null) | Product;
    variant?: (number | null) | ProductVariant;
    /**
     * Lagres automatisk fra variantens visningsnavn da ordren ble opprettet. Brukes ordrett i e-post og kvittering.
     */
    displayName?: string | null;
    variantName?: string | null;
    quantity: number;
    unitPrice: number;
    lineTotal: number;
    /**
     * Andel av rabattkoden som er fordelt på denne linjen.
     */
    discountAmount?: number | null;
    /**
     * Kostpris per enhet på bestillingstidspunktet (uten MVA). Fylles automatisk fra produkt/variant. Kan rettes manuelt.
     */
    unitCost?: number | null;
    /**
     * MVA-sats lagret da ordren ble opprettet. Brukes til å regne omsetning uten MVA.
     */
    vatRate?: number | null;
    /**
     * Beregnes automatisk: kostpris × antall.
     */
    lineCost?: number | null;
    /**
     * Beregnes automatisk: linjesum uten MVA − linjekostnad.
     */
    lineProfit?: number | null;
    id?: string | null;
  }[];
  subtotal: number;
  shipping?: number | null;
  total: number;
  /**
   * Rabattkode brukt på ordren. Tom for ordre uten rabattkode.
   */
  discount?: {
    /**
     * Kan bli tom hvis koden slettes senere — feltene under består.
     */
    promoCode?: (number | null) | PromoCode;
    code?: string | null;
    discountType?: ('percentage' | 'fixed') | null;
    discountValue?: number | null;
    /**
     * Faktisk rabatt i kroner. Gjelder aldri frakt.
     */
    discountAmount?: number | null;
    subtotalBeforeDiscount?: number | null;
    subtotalAfterDiscount?: number | null;
    totalBeforeDiscount?: number | null;
    totalAfterDiscount?: number | null;
  };
  /**
   * Bedriftens reelle fraktkostnad for denne ordren. Kan skille seg fra frakten kunden betalte.
   */
  actualShippingCost?: number | null;
  /**
   * Gebyr til betalingsleverandøren for denne ordren. Beregnes automatisk ved opprettelse hvis aktivert i Økonomiinnstillinger; kan overstyres manuelt.
   */
  paymentFee?: number | null;
  /**
   * Settes automatisk. «Manuelt» når gebyret er endret for hånd.
   */
  paymentFeeSource?: ('auto' | 'manual') | null;
  /**
   * Andre variable kostnader knyttet til ordren (emballasje, retur o.l.).
   */
  extraCosts?: number | null;
  status: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
  /**
   * Settes automatisk når betalingen bekreftes. Brukes som salgsdato i analysen.
   */
  paidAt?: string | null;
  notes?: string | null;
  shippingCarrier?: ('postnord' | 'posten' | 'helthjem') | null;
  /**
   * Sendingsnummeret fra transportøren. Vises i sporingsmailen til kunden.
   */
  trackingNumber?: string | null;
  confirmationEmailSentAt?: string | null;
  adminEmailSentAt?: string | null;
  shippedEmailSentAt?: string | null;
  shippedEmailMessageId?: string | null;
  shippedEmailError?: string | null;
  receiptEmailSentAt?: string | null;
  receiptEmailMessageId?: string | null;
  receiptEmailError?: string | null;
  meta?: {
    fbp?: string | null;
    fbc?: string | null;
    clientIpAddress?: string | null;
    clientUserAgent?: string | null;
    purchaseSentAt?: string | null;
    purchaseEventId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kunder registrert i systemet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Genereres automatisk fra fornavn og etternavn (e-post som reserve).
   */
  displayName?: string | null;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  orders?: (number | Order)[] | null;
  marketingConsent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rabattkoder kunden kan bruke i handlekurven.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  /**
   * Lagres alltid med STORE BOKSTAVER. Kunden kan skrive den som de vil.
   */
  code: string;
  /**
   * Fjern avkryssingen for å skru av koden uten å slette den.
   */
  active?: boolean | null;
  /**
   * Vises kun her i admin — aldri for kunden.
   */
  name?: string | null;
  discountType: 'percentage' | 'fixed';
  /**
   * Prosent (1–100) eller et fast beløp i kroner.
   */
  discountValue: number;
  /**
   * Foreløpig støttes bare gjenbrukbare koder uten bruksgrense. Engangskoder, «kun X ganger» og «én gang per kunde» kommer senere.
   */
  usageMode: 'unlimited';
  /**
   * Antall betalte ordre koden kan brukes på totalt.
   */
  maxUses?: number | null;
  /**
   * La stå tom for å gjelde umiddelbart.
   */
  startsAt?: string | null;
  /**
   * La stå tom for at koden aldri utløper.
   */
  expiresAt?: string | null;
  /**
   * Måles mot summen av de kvalifiserte varelinjene — før rabatt og uten frakt. For en kode uten produktbegrensning er det hele varesummen. La stå tom for ingen minstesum.
   */
  minimumOrderAmount?: number | null;
  /**
   * La stå tom for at koden gjelder alle produkter. Velges produkter, gis rabatt bare på ordrelinjer med disse produktene — varianter følger produktet sitt.
   */
  applicableProducts?: (number | Product)[] | null;
  /**
   * Aktiver dersom rabattkoden tilhører en samarbeidspartner eller influencer.
   */
  isPartnerCode?: boolean | null;
  /**
   * Navnet provisjonen føres på. Vises kun i admin.
   */
  partnerName?: string | null;
  partnerEmail?: string | null;
  partnerPhone?: string | null;
  /**
   * Partnerens kontonummer for manuelle utbetalinger.
   */
  partnerBankAccount?: string | null;
  /**
   * Navnet på kontoeieren dersom det avviker fra partnernavnet.
   */
  partnerAccountOwner?: string | null;
  /**
   * Valgfritt organisasjonsnummer dersom partneren er et firma.
   */
  partnerOrganizationNumber?: string | null;
  /**
   * Provisjon beregnes kun av varesummen, inkludert MVA. Frakt regnes aldri med.
   */
  commissionRate?: number | null;
  /**
   * «Etter rabatt» bruker varesummen minus rabattkoden. «Før rabatt» bruker varesummen slik den var før rabatten. Frakt er utelatt i begge tilfeller.
   */
  commissionBase?: ('orderAfterDiscount' | 'orderBeforeDiscount') | null;
  /**
   * Avtalevilkår, kontaktinfo o.l. Vises aldri for kunden.
   */
  partnerNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registrerte, betalte bruk av rabattkoder. Skrives automatisk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-code-usages".
 */
export interface PromoCodeUsage {
  id: number;
  promoCode?: (number | null) | PromoCode;
  order?: (number | null) | Order;
  orderNumber?: string | null;
  /**
   * Alltid små bokstaver — grunnlaget for «én gang per kunde».
   */
  email?: string | null;
  /**
   * Varer inkl. MVA, uten frakt.
   */
  orderAmountBeforeDiscount?: number | null;
  discountAmount?: number | null;
  /**
   * Varesum før rabatt minus rabatten. Fortsatt uten frakt.
   */
  orderAmountAfterDiscount?: number | null;
  /**
   * Kun for regnskap og rapportering. Inngår aldri i provisjonen.
   */
  shippingAmount?: number | null;
  currency?: string | null;
  /**
   * Var koden en partnerkode da bruken ble registrert?
   */
  isPartnerUsage?: boolean | null;
  /**
   * Navnet slik det var på betalingstidspunktet.
   */
  partnerNameSnapshot?: string | null;
  /**
   * Satsen som faktisk ble brukt. 0 for vanlige rabattkoder.
   */
  commissionRateSnapshot?: number | null;
  commissionBaseSnapshot?: ('orderAfterDiscount' | 'orderBeforeDiscount') | null;
  /**
   * Provisjon beregnes kun av varesummen, inkludert MVA. Frakt regnes aldri med.
   */
  commissionAmount?: number | null;
  /**
   * Tidspunktet betalingen ble bekreftet.
   */
  usedAt?: string | null;
  kustomOrderId?: string | null;
  orderKey?: string | null;
  uniquenessKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registrer en utbetaling som allerede er utført via bank, Vipps eller annen betalingsmåte. Systemet sender aldri penger selv.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-payouts".
 */
export interface PartnerPayout {
  id: number;
  /**
   * Låst etter registrering.
   */
  promoCode: number | PromoCode;
  /**
   * Kopiert fra rabattkoden da utbetalingen ble registrert.
   */
  partnerNameSnapshot: string;
  /**
   * Utbetalt beløp i kroner. Låst etter registrering.
   */
  amount: number;
  payoutDate: string;
  paymentMethod: 'bankTransfer' | 'vipps' | 'other';
  /**
   * Bankreferanse, Vipps-id e.l. Kan endres senere.
   */
  reference?: string | null;
  /**
   * Internt notat. Kan endres senere.
   */
  note?: string | null;
  /**
   * Settes automatisk fra den innloggede brukeren.
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rapporterte markedsføringskostnader. Fordeles på valgt periode i analysen — aldri på enkeltordre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-expenses".
 */
export interface MarketingExpense {
  id: number;
  /**
   * Kostnadsdato. Uten periode nedenfor teller hele beløpet på denne datoen.
   */
  date: string;
  channel: 'meta' | 'google' | 'pinterest' | 'tiktok' | 'snapchat' | 'influencer' | 'annet';
  /**
   * Beløpet du faktisk betalte, inkludert MVA.
   */
  amount: number;
  /**
   * Endres kun dersom fakturaen har en annen MVA-sats.
   */
  vatRate?: number | null;
  /**
   * Beregnes automatisk og brukes i analysen. Du trenger ikke fylle inn noe her.
   */
  amountExVat?: number | null;
  description?: string | null;
  /**
   * F.eks. fakturanummer eller kampanje-ID.
   */
  externalReference?: string | null;
  /**
   * Valgfritt. Sammen med «Periode til» fordeles beløpet jevnt over dagene i perioden.
   */
  periodFrom?: string | null;
  periodTo?: string | null;
  /**
   * Manuell med mindre den er importert automatisk fra Meta, Google Ads, Pinterest Ads eller TikTok Ads.
   */
  source?: ('manual' | 'meta-api' | 'google-ads' | 'pinterest-ads' | 'tiktok-ads') | null;
  /**
   * Deterministisk nøkkel for idempotent import, f.eks. meta:act_123:2026-07-11, google:1234567890:2026-07-11, pinterest:549755885175:2026-07-11 eller tiktok:7012345678901234567:2026-07-11.
   */
  externalKey?: string | null;
  externalAccountId?: string | null;
  externalDate?: string | null;
  lastSyncedAt?: string | null;
  /**
   * Teknisk metadata fra siste import. Inneholder aldri tilgangstoken.
   */
  syncMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundeanmeldelser. Godkjenn, avvis eller skjul før publisering.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  rating: number;
  status: 'pending' | 'approved' | 'rejected' | 'hidden';
  /**
   * Settes automatisk av serveren fra tilknyttet ordre.
   */
  verifiedPurchase?: boolean | null;
  title?: string | null;
  text: string;
  photos?: (number | ReviewPhoto)[] | null;
  customerName: string;
  customerCity?: string | null;
  product: number | Product;
  variantName?: string | null;
  /**
   * Lagret ved innsending, uendret om produktet endres senere.
   */
  productSnapshot?: {
    title?: string | null;
    variantName?: string | null;
    color?: string | null;
  };
  consentToPublishName?: boolean | null;
  consentToPublishPhotos?: boolean | null;
  /**
   * Vises aldri offentlig.
   */
  moderationNote?: string | null;
  order?: (number | null) | Order;
  customer?: (number | null) | Customer;
  invitation?: (number | null) | ReviewInvitation;
  submittedAt?: string | null;
  approvedAt?: string | null;
  helpfulCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundebilder lastet opp med anmeldelser.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-photos".
 */
export interface ReviewPhoto {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Anmeldelsesinvitasjoner (personlige engangslenker).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-invitations".
 */
export interface ReviewInvitation {
  id: number;
  email: string;
  order: number | Order;
  customer?: (number | null) | Customer;
  /**
   * Settes når kunden har sendt inn anmeldelsen.
   */
  review?: (number | null) | Review;
  status: 'active' | 'used' | 'expired' | 'revoked';
  tokenHash: string;
  expiresAt: string;
  usedAt?: string | null;
  sentAt?: string | null;
  resendCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'promo-code-usages';
        value: number | PromoCodeUsage;
      } | null)
    | ({
        relationTo: 'partner-payouts';
        value: number | PartnerPayout;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'marketing-expenses';
        value: number | MarketingExpense;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'review-invitations';
        value: number | ReviewInvitation;
      } | null)
    | ({
        relationTo: 'review-photos';
        value: number | ReviewPhoto;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  price?: T;
  stock?: T;
  costItems?:
    | T
    | {
        name?: T;
        amount?: T;
        id?: T;
      };
  costPrice?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  capacity?:
    | T
    | {
        aa?: T;
        aaa?: T;
        usedCompartments?: T;
      };
  features?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  details?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cartRecommendations?: T;
  salePrice?: T;
  saleStartDate?: T;
  saleEndDate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  section?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  displayName?: T;
  product?: T;
  name?: T;
  colorHex?: T;
  image?: T;
  sku?: T;
  inventory?: T;
  sortOrder?: T;
  videoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  kustomOrderId?: T;
  customer?: T;
  customerInfo?:
    | T
    | {
        email?: T;
        firstName?: T;
        lastName?: T;
        address?: T;
        postalCode?: T;
        city?: T;
        phone?: T;
      };
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        displayName?: T;
        variantName?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        discountAmount?: T;
        unitCost?: T;
        vatRate?: T;
        lineCost?: T;
        lineProfit?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  discount?:
    | T
    | {
        promoCode?: T;
        code?: T;
        discountType?: T;
        discountValue?: T;
        discountAmount?: T;
        subtotalBeforeDiscount?: T;
        subtotalAfterDiscount?: T;
        totalBeforeDiscount?: T;
        totalAfterDiscount?: T;
      };
  actualShippingCost?: T;
  paymentFee?: T;
  paymentFeeSource?: T;
  extraCosts?: T;
  status?: T;
  paidAt?: T;
  notes?: T;
  shippingCarrier?: T;
  trackingNumber?: T;
  confirmationEmailSentAt?: T;
  adminEmailSentAt?: T;
  shippedEmailSentAt?: T;
  shippedEmailMessageId?: T;
  shippedEmailError?: T;
  receiptEmailSentAt?: T;
  receiptEmailMessageId?: T;
  receiptEmailError?: T;
  meta?:
    | T
    | {
        fbp?: T;
        fbc?: T;
        clientIpAddress?: T;
        clientUserAgent?: T;
        purchaseSentAt?: T;
        purchaseEventId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  active?: T;
  name?: T;
  discountType?: T;
  discountValue?: T;
  usageMode?: T;
  maxUses?: T;
  startsAt?: T;
  expiresAt?: T;
  minimumOrderAmount?: T;
  applicableProducts?: T;
  isPartnerCode?: T;
  partnerName?: T;
  partnerEmail?: T;
  partnerPhone?: T;
  partnerBankAccount?: T;
  partnerAccountOwner?: T;
  partnerOrganizationNumber?: T;
  commissionRate?: T;
  commissionBase?: T;
  partnerNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-code-usages_select".
 */
export interface PromoCodeUsagesSelect<T extends boolean = true> {
  promoCode?: T;
  order?: T;
  orderNumber?: T;
  email?: T;
  orderAmountBeforeDiscount?: T;
  discountAmount?: T;
  orderAmountAfterDiscount?: T;
  shippingAmount?: T;
  currency?: T;
  isPartnerUsage?: T;
  partnerNameSnapshot?: T;
  commissionRateSnapshot?: T;
  commissionBaseSnapshot?: T;
  commissionAmount?: T;
  usedAt?: T;
  kustomOrderId?: T;
  orderKey?: T;
  uniquenessKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-payouts_select".
 */
export interface PartnerPayoutsSelect<T extends boolean = true> {
  promoCode?: T;
  partnerNameSnapshot?: T;
  amount?: T;
  payoutDate?: T;
  paymentMethod?: T;
  reference?: T;
  note?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  displayName?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
      };
  orders?: T;
  marketingConsent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-expenses_select".
 */
export interface MarketingExpensesSelect<T extends boolean = true> {
  date?: T;
  channel?: T;
  amount?: T;
  vatRate?: T;
  amountExVat?: T;
  description?: T;
  externalReference?: T;
  periodFrom?: T;
  periodTo?: T;
  source?: T;
  externalKey?: T;
  externalAccountId?: T;
  externalDate?: T;
  lastSyncedAt?: T;
  syncMetadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  rating?: T;
  status?: T;
  verifiedPurchase?: T;
  title?: T;
  text?: T;
  photos?: T;
  customerName?: T;
  customerCity?: T;
  product?: T;
  variantName?: T;
  productSnapshot?:
    | T
    | {
        title?: T;
        variantName?: T;
        color?: T;
      };
  consentToPublishName?: T;
  consentToPublishPhotos?: T;
  moderationNote?: T;
  order?: T;
  customer?: T;
  invitation?: T;
  submittedAt?: T;
  approvedAt?: T;
  helpfulCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-invitations_select".
 */
export interface ReviewInvitationsSelect<T extends boolean = true> {
  email?: T;
  order?: T;
  customer?: T;
  review?: T;
  status?: T;
  tokenHash?: T;
  expiresAt?: T;
  usedAt?: T;
  sentAt?: T;
  resendCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-photos_select".
 */
export interface ReviewPhotosSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Automatisering av gebyr og fraktkostnad, samt MVA-forutsetninger for markedsføring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-settings".
 */
export interface EconomySetting {
  id: number;
  /**
   * Når på: nye ordre får automatisk beregnet betalingsgebyr ved opprettelse.
   */
  kustomEnabled?: boolean | null;
  paymentProvider?: string | null;
  fixedFee?: number | null;
  percentageFee?: number | null;
  /**
   * Kun til MVA-/netto-splitt av gebyret i analysen. Legges IKKE oppå det beregnede gebyret.
   */
  feeVatRate?: number | null;
  calculateFrom?: ('orderTotalInclShipping' | 'productTotalOnly') | null;
  /**
   * MVA-sats som brukes når Meta Ads-kostnader importeres automatisk. Sett til 0 dersom bedriften ikke er MVA-registrert eller fakturaen er uten MVA (reverse charge).
   */
  metaAdsVatRate?: number | null;
  /**
   * Når på: nye ordre får standard faktisk fraktkostnad ved opprettelse (kan overstyres manuelt).
   */
  applyDefaultShippingCost?: boolean | null;
  defaultShippingCost?: number | null;
  /**
   * Fri frakt for kunden betyr ikke null reell fraktkostnad for bedriften.
   */
  freeShippingStillHasCost?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Teknisk lagring for TikTok Ads-autorisasjonen. Opprettes automatisk av «Koble til TikTok».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiktok-connection".
 */
export interface TiktokConnection {
  id: number;
  /**
   * AES-256-GCM-kryptert. Vises aldri, verken i admin eller i API-svar.
   */
  accessTokenEncrypted?: string | null;
  advertiserId?: string | null;
  advertiserName?: string | null;
  currency?: string | null;
  timezone?: string | null;
  connectedAt?: string | null;
  /**
   * Formatet autorisasjonen ble lagret med. En eldre versjon ignoreres, slik at administratoren må koble til på nytt.
   */
  connectionVersion?: number | null;
  /**
   * Av når /advertiser/info/ ble avvist — appen har Reporting, men ikke Ad Account Management. Valuta og tidssone må da oppgis via TIKTOK_ADVERTISER_CURRENCY.
   */
  metadataAvailable?: boolean | null;
  /**
   * Resultatet av én dags testrapport da tilkoblingen ble opprettet.
   */
  reportingOk?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Teknisk lagring for Pinterest Ads-autorisasjonen. Opprettes automatisk av «Koble til».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pinterest-connection".
 */
export interface PinterestConnection {
  id: number;
  /**
   * AES-256-GCM-kryptert. Vises aldri, verken i admin eller i API-svar.
   */
  accessTokenEncrypted?: string | null;
  /**
   * AES-256-GCM-kryptert. Roteres av Pinterest ved hver fornyelse og erstattes atomisk.
   */
  refreshTokenEncrypted?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  /**
   * Tilgangsnivået Pinterest faktisk innvilget.
   */
  scope?: string | null;
  tokenType?: string | null;
  connectedAt?: string | null;
  lastRefreshedAt?: string | null;
  connectionStatus?: ('disconnected' | 'connected' | 'reauthorization_required') | null;
  /**
   * Kun en kort, intern feilkode (f.eks. invalid_grant). Aldri Pinterests rå svar og aldri et token.
   */
  lastOAuthError?: string | null;
  /**
   * Økes ved hver rotasjon. Brukes som compare-and-swap slik at to samtidige synkroniseringer ikke kan fornye med det samme gamle fornyelsestokenet.
   */
  tokenVersion?: number | null;
  /**
   * Settes mens en fornyelse pågår, og utløper av seg selv slik at en avbrutt prosess ikke låser integrasjonen permanent.
   */
  refreshLockExpiresAt?: string | null;
  /**
   * Formatet autorisasjonen ble lagret med. En eldre versjon ignoreres, slik at administratoren må koble til på nytt.
   */
  connectionVersion?: number | null;
  /**
   * SHA-256 av state-verdien. Selve verdien lagres aldri.
   */
  pendingStateHash?: string | null;
  pendingStateExpiresAt?: string | null;
  pendingStateUserId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "economy-settings_select".
 */
export interface EconomySettingsSelect<T extends boolean = true> {
  kustomEnabled?: T;
  paymentProvider?: T;
  fixedFee?: T;
  percentageFee?: T;
  feeVatRate?: T;
  calculateFrom?: T;
  metaAdsVatRate?: T;
  applyDefaultShippingCost?: T;
  defaultShippingCost?: T;
  freeShippingStillHasCost?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tiktok-connection_select".
 */
export interface TiktokConnectionSelect<T extends boolean = true> {
  accessTokenEncrypted?: T;
  advertiserId?: T;
  advertiserName?: T;
  currency?: T;
  timezone?: T;
  connectedAt?: T;
  connectionVersion?: T;
  metadataAvailable?: T;
  reportingOk?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pinterest-connection_select".
 */
export interface PinterestConnectionSelect<T extends boolean = true> {
  accessTokenEncrypted?: T;
  refreshTokenEncrypted?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  tokenType?: T;
  connectedAt?: T;
  lastRefreshedAt?: T;
  connectionStatus?: T;
  lastOAuthError?: T;
  tokenVersion?: T;
  refreshLockExpiresAt?: T;
  connectionVersion?: T;
  pendingStateHash?: T;
  pendingStateExpiresAt?: T;
  pendingStateUserId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}